import { useState } from 'react'

function avg(arr) {
  const vals = arr.filter((v) => v !== null && v !== undefined)
  if (!vals.length) return null
  return (vals.reduce((a, b) => a + b, 0) / vals.length).toFixed(1)
}

function buildReport(logs) {
  if (!logs.length) return 'No entries yet — log a few days to generate a visit-prep summary.'

  const sorted = [...logs].sort((a, b) => a.log_date.localeCompare(b.log_date))
  const start = sorted[0].log_date
  const end = sorted[sorted.length - 1].log_date
  const totalHF = sorted.reduce((a, l) => a + (l.hot_flashes || 0), 0)
  const daysWithSweats = sorted.filter((l) => l.night_sweats).length
  const avgSleepHours = avg(sorted.map((l) => l.sleep_hours))
  const avgSleepQuality = avg(sorted.map((l) => l.sleep_quality))
  const avgMood = avg(sorted.map((l) => l.mood))
  const avgFog = avg(sorted.map((l) => l.brain_fog))
  const avgJoints = avg(sorted.map((l) => l.joint_aches))
  const cycleCounts = sorted.reduce((acc, l) => {
    acc[l.cycle_status] = (acc[l.cycle_status] || 0) + 1
    return acc
  }, {})

  const notesWithDates = sorted.filter((l) => l.notes && l.notes.trim()).slice(-5)

  let report = `SOLSTICE — SYMPTOM SUMMARY FOR CLINICAL VISIT\n`
  report += `Period covered: ${start} to ${end} (${sorted.length} logged days)\n`
  report += `${'-'.repeat(50)}\n\n`

  report += `HOT FLASHES\n`
  report += `  Total episodes logged: ${totalHF}\n`
  report += `  Average per logged day: ${(totalHF / sorted.length).toFixed(1)}\n`
  report += `  Night sweats reported on ${daysWithSweats} of ${sorted.length} days\n\n`

  report += `SLEEP\n`
  report += `  Average hours per night: ${avgSleepHours ?? 'not tracked'}\n`
  report += `  Average self-rated quality (1-5): ${avgSleepQuality ?? 'not tracked'}\n\n`

  report += `MOOD & COGNITION\n`
  report += `  Average mood (1 low - 5 good): ${avgMood ?? 'not tracked'}\n`
  report += `  Average brain fog (1 clear - 5 foggy): ${avgFog ?? 'not tracked'}\n\n`

  report += `PHYSICAL\n`
  report += `  Average joint ache severity (1 none - 5 severe): ${avgJoints ?? 'not tracked'}\n\n`

  report += `CYCLE\n`
  Object.entries(cycleCounts).forEach(([status, count]) => {
    report += `  ${status}: ${count} day(s)\n`
  })
  report += `\n`

  if (notesWithDates.length) {
    report += `RECENT NOTES\n`
    notesWithDates.forEach((l) => {
      report += `  ${l.log_date}: ${l.notes.trim()}\n`
    })
    report += `\n`
  }

  report += `${'-'.repeat(50)}\n`
  report += `This summary reflects self-reported daily logs only. It is not a diagnosis\n`
  report += `and does not recommend any treatment. Generated by Solstice for use as a\n`
  report += `conversation starting point with a healthcare provider.`

  return report
}

export default function DoctorReport({ logs }) {
  const [copied, setCopied] = useState(false)
  const report = buildReport(logs)

  async function handleCopy() {
    await navigator.clipboard.writeText(report)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="card">
      <h2>Doctor visit report</h2>
      <p className="sub">A copyable summary of your logged patterns — built for the appointment, not a diagnosis.</p>
      <pre className="report-box">{report}</pre>
      <div style={{ marginTop: 14 }}>
        <button className="ghost-btn" onClick={handleCopy}>{copied ? 'Copied' : 'Copy to clipboard'}</button>
      </div>
    </div>
  )
}
